# Generated by Django 3.0.3 on 2020-02-26 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taxishare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('birth_date', models.DateField(null=True, verbose_name='生年月日')),
                ('sex', models.IntegerField(null=True, verbose_name='性別')),
                ('origin_latitude', models.FloatField(default=35.696739, verbose_name='出発地の緯度')),
                ('origin_longitude', models.FloatField(default=139.814484, verbose_name='出発地の経度')),
                ('desitination_latitude', models.FloatField(null=True, verbose_name='目的地の緯度')),
                ('desitination_longitude', models.FloatField(null=True, verbose_name='目的地の経度')),
                ('is_staff', models.BooleanField(default=False, help_text='ユーザーが管理サイトにログインするかどうか指定する。', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='ユーザーがアクティブとするかどうか指定する。アカウントを削除する代わりに選ばない。', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', taxishare.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'タクシー',
                'verbose_name_plural': 'タクシー',
            },
        ),
    ]
